-- Seed the public agent directory.
-- 50 rows are Marketing's verified seed_for_migration (2026-10-06).
-- Five more are the published Hire us packages. No other names are added.
-- Idempotent: skip a row when that name already exists (case-insensitive)
-- or when the id is already present. Does not update or hide existing rows.
-- ip_hash is null, so these rows do not count toward the public post rate limit.
--
-- Preview builds skip this file. VERCEL_ENV=preview uses the production
-- DATABASE_URL, and a preview build must not insert these rows into production.
-- Production, local, and tests apply it. See scripts/migration-plan.mjs.

insert into agent_listings (id, name, skills, pitch, contact, link, ip_hash, created_at)
select v.id, v.name, v.skills, v.pitch, v.contact, v.link, null, v.created_at
from (
  values
  ('agent_19d84f7757233109b35bec49', 'Agent directory boost', array['directory listing', 'offer copy', 'one push']::text[], 'We list your agent on the public directory, write a clear offer, and push it once where that is allowed. $49. We do not run your agent, and we do not promise new customers. Listing yourself is still free.', 'support@agent-control.net', 'https://agent-control.net/hire', timestamptz '2026-10-06 18:00:00+00' - interval '4 seconds'),
  ('agent_d48e0f1a9d8377643e184ffd', 'Job pack (5 posts)', array['hiring briefs', 'job board', 'five posts']::text[], 'We write and post 5 real hiring briefs on the job board. $79. We do not hire the worker. You still agree payment with the worker when you say the work is done. Paying through Agent Control for those jobs is not switched on.', 'support@agent-control.net', 'https://agent-control.net/hire', timestamptz '2026-10-06 18:00:00+00' - interval '3 seconds'),
  ('agent_de603b189d893d5796258787', 'Action Gate setup', array['Action Gate', 'setup', 'paid gate']::text[], 'We wire Action Gate into your agent setup and get you to a working paid gate. $149, one time. The $49 a month Action Gate plan is a separate subscription.', 'support@agent-control.net', 'https://agent-control.net/hire', timestamptz '2026-10-06 18:00:00+00' - interval '2 seconds'),
  ('agent_e37c442313ae226c980da3b8', 'Outreach kit', array['outreach copy', 'target list']::text[], '10 human-sounding outreach messages, plus a target list of people who need agents or a paid gate. $199. We do not send the messages, and we do not buy ads.', 'support@agent-control.net', 'https://agent-control.net/hire', timestamptz '2026-10-06 18:00:00+00' - interval '1 seconds'),
  ('agent_9806d81759eac5ed84cdc3de', 'Done-for-you sprint (1 week)', array['research', 'site copy', 'agent ops', 'shipping']::text[], 'One scoped outcome for one week: research, site copy, agent ops, or a small shipping task. Mid-week check and handoff notes. $499. Work past that outcome is a new package.', 'support@agent-control.net', 'https://agent-control.net/hire', timestamptz '2026-10-06 18:00:00+00' - interval '0 seconds'),
  ('agent_ee04cdf9913a243fbabcfb95', 'Ops Agent', array['Vercel deploys', 'DNS', 'env checks', 'release ops']::text[], 'Ops help for Vercel deploys, DNS, env checks, and release steps for agent-control.net. Contact support@agent-control.net.', 'support@agent-control.net', 'https://agent-control.net', timestamptz '2026-10-06 11:00:00+00' + interval '0 seconds'),
  ('agent_76db9244144ac1227cb078b1', 'AutoGPT', array['agentic ai', 'agents', 'ai', 'artificial intelligence', 'autonomous agents', 'AI agent']::text[], 'AutoGPT is the vision of accessible AI for everyone, to use and to build on. Our mission is to provide the tools, so that you can focus on what matters. Listed from public registry - unclaimed.', 'https://agpt.co', 'https://agpt.co', timestamptz '2026-10-06 11:00:00+00' + interval '1 seconds'),
  ('agent_be99453ea3c8b58fb57ff75b', 'firecrawl', array['ai', 'ai agents', 'ai crawler', 'ai scraping', 'ai search', 'AI agent']::text[], 'The web data API to search, scrape, and interact at scale. 🔥 Listed from public registry - unclaimed.', 'https://firecrawl.dev', 'https://firecrawl.dev', timestamptz '2026-10-06 11:00:00+00' + interval '2 seconds'),
  ('agent_9f44cbf4d2fecec3ebd3da02', 'dify', array['agent', 'agentic ai', 'agentic framework', 'agentic workflow', 'ai', 'AI agent']::text[], 'Build Agentic workflows, RAG pipelines, with rich AI model and tool support on one collaborative workspace. Deploy on cloud, VPC, or self-hosted, so teams move from prototype to production without rebuilding the stack. Listed from public registry - unclaimed.', 'https://dify.ai', 'https://dify.ai', timestamptz '2026-10-06 11:00:00+00' + interval '3 seconds'),
  ('agent_df004f285dfa3db5b7c307bc', 'langflow', array['agents', 'chatgpt', 'generative ai', 'large language models', 'multiagent', 'AI agent']::text[], 'Langflow is a powerful tool for building and deploying AI-powered agents and workflows. Listed from public registry - unclaimed.', 'https://www.langflow.org/', 'https://www.langflow.org/', timestamptz '2026-10-06 11:00:00+00' + interval '4 seconds'),
  ('agent_96026359248d1dfd6dfa0490', 'opencode', array['AI agent']::text[], 'The open source coding agent. Listed from public registry - unclaimed.', 'https://anoma.ly', 'https://anoma.ly', timestamptz '2026-10-06 11:00:00+00' + interval '5 seconds'),
  ('agent_b8ae338f7ff841259bf5bbd1', 'ollama', array['deepseek', 'gemma', 'gemma3', 'glm', 'go', 'AI agent']::text[], 'Get up and running with Kimi, GLM, MiniMax, DeepSeek, gpt-oss, Qwen, Gemma and other models. Listed from public registry - unclaimed.', 'https://ollama.com', 'https://ollama.com', timestamptz '2026-10-06 11:00:00+00' + interval '6 seconds'),
  ('agent_bb898c8dcee72371ce41c77d', 'openclaw', array['ai', 'assistant', 'crustacean', 'molty', 'openclaw', 'AI agent']::text[], 'The AI that really does things. Any OS. Any Platform. The lobster way. 🦞 Listed from public registry - unclaimed.', 'https://openclaw.ai', 'https://openclaw.ai', timestamptz '2026-10-06 11:00:00+00' + interval '7 seconds'),
  ('agent_8b0ed0eda9fb1f8f6eb4f3e7', 'hermes-agent', array['ai', 'ai agent', 'ai agents', 'anthropic', 'chatgpt', 'AI agent']::text[], 'The agent that grows with you Listed from public registry - unclaimed.', 'https://nousresearch.com', 'https://nousresearch.com', timestamptz '2026-10-06 11:00:00+00' + interval '8 seconds'),
  ('agent_327e06dbb7b7edea32ffce30', 'claude-code', array['code', 'hr', 'coding', 'AI agent']::text[], 'Claude Code is an agentic coding tool that lives in your terminal, understands your codebase, and helps you code faster by executing routine tasks, explaining complex code, and handling git workflows - all through natur… Listed from public registry - unclaimed.', 'https://anthropic.com', 'https://anthropic.com', timestamptz '2026-10-06 11:00:00+00' + interval '9 seconds'),
  ('agent_22ec49c788897a9125832e0a', 'codex', array['code', 'coding', 'AI agent']::text[], 'Lightweight coding agent that runs in your terminal Listed from public registry - unclaimed.', 'https://openai.com/', 'https://openai.com/', timestamptz '2026-10-06 11:00:00+00' + interval '10 seconds'),
  ('agent_f2e4099af3e3110cdf3efa1f', 'langchain', array['agents', 'ai', 'ai agents', 'anthropic', 'chatgpt', 'AI agent']::text[], 'The agent engineering platform. Listed from public registry - unclaimed.', 'https://www.langchain.com', 'https://www.langchain.com', timestamptz '2026-10-06 11:00:00+00' + interval '11 seconds'),
  ('agent_22dcdc22f72d864bae559233', 'open-webui', array['ai', 'llm', 'llm ui', 'llm webui', 'llms', 'AI agent']::text[], 'User-friendly AI Interface (Supports Ollama, OpenAI API, ...) Listed from public registry - unclaimed.', 'https://openwebui.com', 'https://openwebui.com', timestamptz '2026-10-06 11:00:00+00' + interval '12 seconds'),
  ('agent_8a8445b6c7abcea300a15d91', 'agency-agents', array['personal', 'AI agent']::text[], 'A complete AI agency at your fingertips - From frontend wizards to Reddit community ninjas, from whimsy injectors to reality checkers. Each agent is a specialized expert with personality, processes, and proven deliverab… Listed from public registry - unclaimed.', 'https://msitarzewski.com', 'https://msitarzewski.com', timestamptz '2026-10-06 11:00:00+00' + interval '13 seconds'),
  ('agent_5382b51ca2e32ee11d06a9d6', 'superpowers', array['framework', 'coding', 'AI agent']::text[], 'An agentic skills framework & software development methodology that works. Listed from public registry - unclaimed.', 'https://github.com/obra/superpowers', 'https://github.com/obra/superpowers', timestamptz '2026-10-06 11:00:00+00' + interval '14 seconds'),
  ('agent_6e4c0f891da3daf582c458ad', '2kw.ai', array['MCP']::text[], 'EU-hosted AI platform: OpenAI-compatible LLM gateway, document extraction, transcription, agents. Listed from public registry - unclaimed.', 'https://2kw.ai', 'https://2kw.ai', timestamptz '2026-10-06 11:00:00+00' + interval '15 seconds'),
  ('agent_151c14459998c3179af50209', 'AFG: agents hire agents (test money)', array['MCP']::text[], 'Sandbox marketplace where AI agents hire agents for verified outcomes. Test money only. Listed from public registry - unclaimed.', 'https://afg.ai', 'https://afg.ai', timestamptz '2026-10-06 11:00:00+00' + interval '16 seconds'),
  ('agent_dd85179440da5d48ab8368fe', 'Agentic Shelf', array['MCP']::text[], 'Hosted MCP for e-commerce: live product catalog, stock, and pricing for AI agents. Listed from public registry - unclaimed.', 'https://www.agenticshelf.ai', 'https://www.agenticshelf.ai', timestamptz '2026-10-06 11:00:00+00' + interval '17 seconds'),
  ('agent_f75631b502ed9d6253f3bb25', 'adside', array['MCP']::text[], 'AI agents that manage paid ads on Meta, LinkedIn, and Google Ads from any MCP client. Listed from public registry - unclaimed.', 'https://www.adside.ai', 'https://www.adside.ai', timestamptz '2026-10-06 11:00:00+00' + interval '18 seconds'),
  ('agent_a399c8bb76afc6b4efd0fa87', 'docs-mcp', array['MCP']::text[], 'Remote MCP server for Tandem docs, install guides, SDKs, workflows, and agent setup help. Listed from public registry - unclaimed.', 'https://tandem.ac/docs-mcp', 'https://tandem.ac/docs-mcp', timestamptz '2026-10-06 11:00:00+00' + interval '19 seconds'),
  ('agent_16326705d28fb055d91bcae3', 'Adrails', array['MCP']::text[], 'AI agents that build, test and monitor Meta Ads and Google Ads campaigns from your real data. Listed from public registry - unclaimed.', 'https://adrails.ai/mcp', 'https://adrails.ai/mcp', timestamptz '2026-10-06 11:00:00+00' + interval '20 seconds'),
  ('agent_f21a02784a8c04cf27a82726', 'Aether Wealth', array['MCP']::text[], 'Aether Wealth MCP for AI assistants: trades, alerts, market data, macro calendar & indicators. Listed from public registry - unclaimed.', 'https://aetherwealth.ai/mcp', 'https://aetherwealth.ai/mcp', timestamptz '2026-10-06 11:00:00+00' + interval '21 seconds'),
  ('agent_0f184a9ba526bf68b18dc11a', 'Affiliate Networks MCP', array['MCP']::text[], 'Affiliate network reporting in your AI client. Bring your own keys. Most adapters experimental. Listed from public registry - unclaimed.', 'https://agenticaffiliate.ai', 'https://agenticaffiliate.ai', timestamptz '2026-10-06 11:00:00+00' + interval '22 seconds'),
  ('agent_653434a9c9ebf5ea0c8550c0', 'AgentDM: Agent to Agent Communication Platform', array['MCP']::text[], 'Agent communication platform for agent to agent messaging via MCP. Messages, channels, skills. Listed from public registry - unclaimed.', 'https://agentdm.ai', 'https://agentdm.ai', timestamptz '2026-10-06 11:00:00+00' + interval '23 seconds'),
  ('agent_73b564e449a897b3e3588b00', 'AgentGates', array['MCP']::text[], 'Confidential compute and inference sold to agents over x402 USDC, plus an agent wallet over MCP. Listed from public registry - unclaimed.', 'https://agentgates.ai', 'https://agentgates.ai', timestamptz '2026-10-06 11:00:00+00' + interval '24 seconds'),
  ('agent_889c39761cfd28a4e030728b', '1325.AI', array['MCP']::text[], 'Verified directory of 47,000+ Black-owned U.S. businesses. Search, profiles, maps, rewards. Listed from public registry - unclaimed.', 'https://1325.ai', 'https://1325.ai', timestamptz '2026-10-06 11:00:00+00' + interval '25 seconds'),
  ('agent_2e9c6778b4f8eba5a14496a9', 'ABMeter', array['MCP']::text[], 'Run A/B experiments through your AI assistant. SDKs for Ruby, Python, JS, Node, React Native, Go. Listed from public registry - unclaimed.', 'https://abmeter.ai', 'https://abmeter.ai', timestamptz '2026-10-06 11:00:00+00' + interval '26 seconds'),
  ('agent_7b43cd9785ec5b227ceae3b8', 'AdAdvisor MCP Server', array['MCP']::text[], 'Query Meta Ads performance data — accounts, campaigns, ad sets, ads, metrics & settings. Listed from public registry - unclaimed.', 'https://www.adadvisor.ai/docs/user-guide/getting-started-with-mcp?utm_source=mcp-registry', 'https://www.adadvisor.ai/docs/user-guide/getting-started-with-mcp?utm_source=mcp-registry', timestamptz '2026-10-06 11:00:00+00' + interval '27 seconds'),
  ('agent_f14f229f632a5b21c31e0952', 'Adako: ad ops for AI assistants', array['MCP']::text[], 'Google, Meta, LinkedIn and ChatGPT Ads for AI assistants. Every change needs your approval. Listed from public registry - unclaimed.', 'https://adako.ai/docs', 'https://adako.ai/docs', timestamptz '2026-10-06 11:00:00+00' + interval '28 seconds'),
  ('agent_7fefe8fdba4908541911785d', 'Adsap', array['MCP']::text[], 'Launch and manage Meta and Google Ads from your AI assistant. You approve every change first. Listed from public registry - unclaimed.', 'https://adsap.ai', 'https://adsap.ai', timestamptz '2026-10-06 11:00:00+00' + interval '29 seconds'),
  ('agent_6d305c5ce6bba71cc0a5ccce', 'Advisors AI — Route a Store Need to a Service', array['MCP']::text[], 'Describe a store''s problem: get the matching service, its fixed price, and a request link. Listed from public registry - unclaimed.', 'https://advisorsai.ai', 'https://advisorsai.ai', timestamptz '2026-10-06 11:00:00+00' + interval '30 seconds'),
  ('agent_bfcc7d0a45f4c9c6c17784c6', 'Agentic News', array['MCP']::text[], 'AI-powered news intelligence — 21 tools for personalized monitoring, briefings, and semantic search Listed from public registry - unclaimed.', 'https://agentic-news.ai/mcp', 'https://agentic-news.ai/mcp', timestamptz '2026-10-06 11:00:00+00' + interval '31 seconds'),
  ('agent_ff44a6093b1e5ff920b38f4b', 'Agentic Terminal Directory', array['MCP']::text[], 'Verified merchants accepting agentic payments on Lightning/L402/BOLT12/USDT — search, verify, pay. Listed from public registry - unclaimed.', 'https://agenticterminal.ai', 'https://agenticterminal.ai', timestamptz '2026-10-06 11:00:00+00' + interval '32 seconds'),
  ('agent_353f9ce4e271d7f9ad8915ba', 'AgenticBooks', array['MCP']::text[], 'Startup books from live bank and billing feeds: P&L, balances, approvals, period close. Listed from public registry - unclaimed.', 'https://www.agenticbooks.ai', 'https://www.agenticbooks.ai', timestamptz '2026-10-06 11:00:00+00' + interval '33 seconds'),
  ('agent_bdb44b429679073e53ed5390', 'Bureau public reader', array['MCP']::text[], 'Bureau-operated public read-only MCP service for public Context Packets and Cases. Listed from public registry - unclaimed.', 'https://thebureauoflostcontext.agency', 'https://thebureauoflostcontext.agency', timestamptz '2026-10-06 11:00:00+00' + interval '34 seconds'),
  ('agent_0a9cfae6240a562ac9b24e48', 'JustIdea Agency', array['MCP']::text[], 'Services, prices, inquiries and free analytics and AI visibility scans by JustIdea, a Polish agency. Listed from public registry - unclaimed.', 'https://justidea.agency/', 'https://justidea.agency/', timestamptz '2026-10-06 11:00:00+00' + interval '35 seconds'),
  ('agent_2aad84589c025c5ba3e1a9e0', 'adtest-mcp', array['MCP']::text[], 'AI-only ad scoring for Claude: score image, video or text ads on 13 dimensions before you spend. Listed from public registry - unclaimed.', 'https://adtest.ai/', 'https://adtest.ai/', timestamptz '2026-10-06 11:00:00+00' + interval '36 seconds'),
  ('agent_705488a9a809ff93824fc0df', 'agent-bev', array['MCP']::text[], 'The world''s largest agentic B2B hub for beer, wine and spirits. Powered by CUVEE. Trade only. Listed from public registry - unclaimed.', 'https://agent-bev.ai', 'https://agent-bev.ai', timestamptz '2026-10-06 11:00:00+00' + interval '37 seconds'),
  ('agent_8d99f5c29e24193942ffe5b5', '1ClickWebsite', array['MCP']::text[], 'Build and edit WordPress websites for local service businesses and run Lead Gen demo-site batches. Listed from public registry - unclaimed.', 'https://www.1clickwebsite.ai/docs/mcp', 'https://www.1clickwebsite.ai/docs/mcp', timestamptz '2026-10-06 11:00:00+00' + interval '38 seconds'),
  ('agent_b5084b7c3bbe8f4bca16cee0', 'AFMR Discovery', array['MCP']::text[], 'Read AFMR failure modes and discover scoped attestation and lift-evidence contracts. Listed from public registry - unclaimed.', 'https://afmr.ai/', 'https://afmr.ai/', timestamptz '2026-10-06 11:00:00+00' + interval '39 seconds'),
  ('agent_8d4a4deb7a31c8d7936acf38', 'Aard', array['MCP']::text[], 'Official statistics from 170+ publishers, resolved from natural language with provenance. Listed from public registry - unclaimed.', 'https://aard.ai/mcp', 'https://aard.ai/mcp', timestamptz '2026-10-06 11:00:00+00' + interval '40 seconds'),
  ('agent_86ead0e6901a4a452e20451e', 'Adrio', array['MCP']::text[], 'Research competitor Meta ads, manage brand angles and audiences, and brief Spark to create ads. Listed from public registry - unclaimed.', 'https://adrio.ai', 'https://adrio.ai', timestamptz '2026-10-06 11:00:00+00' + interval '41 seconds'),
  ('agent_254c237afa9c797843b41b8e', 'Aevia', array['MCP']::text[], 'AI-powered life cycle assessment and modelling: connect to LCA databases, build and analyze systems Listed from public registry - unclaimed.', 'https://aeviamodeler.ai/mcp?src=mcp-registry', 'https://aeviamodeler.ai/mcp?src=mcp-registry', timestamptz '2026-10-06 11:00:00+00' + interval '42 seconds'),
  ('agent_95ef02f753c401bed86117b1', 'CounterScript - Drug Price Benchmarks', array['MCP']::text[], 'Free US drug-price benchmarks from federal data (CMS NADAC): a benchmark, not a price anyone owes. Listed from public registry - unclaimed.', 'https://rx.agentlookups.ai', 'https://rx.agentlookups.ai', timestamptz '2026-10-06 11:00:00+00' + interval '43 seconds'),
  ('agent_95158394598b7cd05f72b552', 'Getlead', array['MCP']::text[], 'Find B2B leads with verified work emails, find and verify emails, and run cold email outreach. Listed from public registry - unclaimed.', 'https://getle.ad/mcp', 'https://getle.ad/mcp', timestamptz '2026-10-06 11:00:00+00' + interval '44 seconds'),
  ('agent_acde64633ed4e9f08fa1905b', 'GreenLight - Plug-in Solar Law Registry', array['MCP']::text[], 'US plug-in solar (balcony solar) law registry with a daily UL 3700 certification watch. Listed from public registry - unclaimed.', 'https://solar.agentlookups.ai', 'https://solar.agentlookups.ai', timestamptz '2026-10-06 11:00:00+00' + interval '45 seconds'),
  ('agent_6d92e66825cb8a02af26ac5f', 'GroundTruth - Environmental Records', array['MCP']::text[], 'Federal environmental records near any US location, with dates and provenance; never a safety score. Listed from public registry - unclaimed.', 'https://env.agentlookups.ai', 'https://env.agentlookups.ai', timestamptz '2026-10-06 11:00:00+00' + interval '46 seconds'),
  ('agent_aeab4e1fd63c02cf6ebc6a37', 'Inside Ads', array['MCP']::text[], 'Telegram ad exchange: estimate reach and cost with no account, then create and run campaigns. Listed from public registry - unclaimed.', 'https://inside.ad', 'https://inside.ad', timestamptz '2026-10-06 11:00:00+00' + interval '47 seconds'),
  ('agent_67311858340469eab71a01ba', 'Plumbline - Contractor License Checks', array['MCP']::text[], 'Free contractor-license checks from official state records; a no-match never proves unlicensed. Listed from public registry - unclaimed.', 'https://contractors.agentlookups.ai', 'https://contractors.agentlookups.ai', timestamptz '2026-10-06 11:00:00+00' + interval '48 seconds'),
  ('agent_4430926955480094474e2a2c', 'Pre-Trip compliance scanner', array['MCP']::text[], 'Screen regulated-health marketing copy against source-cited rulesets, all 50 states. Listed from public registry - unclaimed.', 'https://scan.kesey.agency/developers/', 'https://scan.kesey.agency/developers/', timestamptz '2026-10-06 11:00:00+00' + interval '49 seconds')
) as v(id, name, skills, pitch, contact, link, created_at)
where not exists (
  select 1
  from agent_listings existing
  where lower(existing.name) = lower(v.name)
)
on conflict (id) do nothing;
