/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as MeterPayRouteImport } from './routes/meter.pay'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppPoliciesRouteImport } from './routes/_app/policies'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as OauthRegisterRouteImport } from './routes/oauth/register'
import { Route as OauthTokenRouteImport } from './routes/oauth/token'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents.index'
import { Route as AppAgentsIdRouteImport } from './routes/_app/agents.$id'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing.index'
import { Route as AppBillingPayRouteImport } from './routes/_app/billing.pay'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1CheckRouteImport } from './routes/api/v1/check'
import { Route as ApiV1McpRouteImport } from './routes/api/v1/mcp'
import { Route as ApiV1ApprovalsIdRouteImport } from './routes/api/v1/approvals.$id'
import { Route as ApiV1BillingCheckoutRouteImport } from './routes/api/v1/billing.checkout'
import { Route as ApiV1BillingConfigRouteImport } from './routes/api/v1/billing.config'
import { Route as ApiV1BillingHeliusRouteImport } from './routes/api/v1/billing.helius'
import { Route as ApiV1BillingHeliusSetupRouteImport } from './routes/api/v1/billing.helius-setup'
import { Route as ApiV1BillingInvoiceRouteImport } from './routes/api/v1/billing.invoice'
import { Route as ApiV1BillingWatchRouteImport } from './routes/api/v1/billing.watch'
import { Route as ApiV1InternalMeterRouteImport } from './routes/api/v1/internal/meter'
import { Route as ApiV1InternalStatsRouteImport } from './routes/api/v1/internal/stats'
import { Route as ApiV1InternalTrialMailRouteImport } from './routes/api/v1/internal/trial-mail'
import { Route as ApiV1MeterSplatRouteImport } from './routes/api/v1/meter.$'
import { Route as ApiV1StorefrontAttachRouteImport } from './routes/api/v1/storefront.attach'
import { Route as ApiV1StorefrontCheckoutRouteImport } from './routes/api/v1/storefront.checkout'
import { Route as ApiV1StorefrontPricingRouteImport } from './routes/api/v1/storefront.pricing'
import { Route as ApiV1StorefrontStatusRouteImport } from './routes/api/v1/storefront.status'
import { Route as ApiV1StorefrontTrialRouteImport } from './routes/api/v1/storefront.trial'
import { Route as ApiV1InternalMeterInvoicesRouteImport } from './routes/api/v1/internal/meter.invoices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const MeterPayRoute = MeterPayRouteImport.update({
  id: '/meter/pay',
  path: '/meter/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRegisterRoute = OauthRegisterRouteImport.update({
  id: '/oauth/register',
  path: '/oauth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTokenRoute = OauthTokenRouteImport.update({
  id: '/oauth/token',
  path: '/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppAgentsIdRoute = AppAgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingPayRoute = AppBillingPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AppBillingRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CheckRoute = ApiV1CheckRouteImport.update({
  id: '/api/v1/check',
  path: '/api/v1/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1McpRoute = ApiV1McpRouteImport.update({
  id: '/api/v1/mcp',
  path: '/api/v1/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ApprovalsIdRoute = ApiV1ApprovalsIdRouteImport.update({
  id: '/api/v1/approvals/$id',
  path: '/api/v1/approvals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingCheckoutRoute = ApiV1BillingCheckoutRouteImport.update({
  id: '/api/v1/billing/checkout',
  path: '/api/v1/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingConfigRoute = ApiV1BillingConfigRouteImport.update({
  id: '/api/v1/billing/config',
  path: '/api/v1/billing/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingHeliusRoute = ApiV1BillingHeliusRouteImport.update({
  id: '/api/v1/billing/helius',
  path: '/api/v1/billing/helius',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingHeliusSetupRoute = ApiV1BillingHeliusSetupRouteImport.update({
  id: '/api/v1/billing/helius-setup',
  path: '/api/v1/billing/helius-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingInvoiceRoute = ApiV1BillingInvoiceRouteImport.update({
  id: '/api/v1/billing/invoice',
  path: '/api/v1/billing/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BillingWatchRoute = ApiV1BillingWatchRouteImport.update({
  id: '/api/v1/billing/watch',
  path: '/api/v1/billing/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InternalMeterRoute = ApiV1InternalMeterRouteImport.update({
  id: '/api/v1/internal/meter',
  path: '/api/v1/internal/meter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InternalStatsRoute = ApiV1InternalStatsRouteImport.update({
  id: '/api/v1/internal/stats',
  path: '/api/v1/internal/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InternalTrialMailRoute = ApiV1InternalTrialMailRouteImport.update({
  id: '/api/v1/internal/trial-mail',
  path: '/api/v1/internal/trial-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeterSplatRoute = ApiV1MeterSplatRouteImport.update({
  id: '/api/v1/meter/$',
  path: '/api/v1/meter/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StorefrontAttachRoute = ApiV1StorefrontAttachRouteImport.update({
  id: '/api/v1/storefront/attach',
  path: '/api/v1/storefront/attach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StorefrontCheckoutRoute = ApiV1StorefrontCheckoutRouteImport.update({
  id: '/api/v1/storefront/checkout',
  path: '/api/v1/storefront/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StorefrontPricingRoute = ApiV1StorefrontPricingRouteImport.update({
  id: '/api/v1/storefront/pricing',
  path: '/api/v1/storefront/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StorefrontStatusRoute = ApiV1StorefrontStatusRouteImport.update({
  id: '/api/v1/storefront/status',
  path: '/api/v1/storefront/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1StorefrontTrialRoute = ApiV1StorefrontTrialRouteImport.update({
  id: '/api/v1/storefront/trial',
  path: '/api/v1/storefront/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1InternalMeterInvoicesRoute =
  ApiV1InternalMeterInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => ApiV1InternalMeterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/meter/pay': typeof MeterPayRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/billing': typeof AppBillingRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/policies': typeof AppPoliciesRoute
  '/settings': typeof AppSettingsRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/agents/$id': typeof AppAgentsIdRoute
  '/billing/pay': typeof AppBillingPayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/billing/': typeof AppBillingIndexRoute
  '/api/v1/approvals/$id': typeof ApiV1ApprovalsIdRoute
  '/api/v1/billing/checkout': typeof ApiV1BillingCheckoutRoute
  '/api/v1/billing/config': typeof ApiV1BillingConfigRoute
  '/api/v1/billing/helius': typeof ApiV1BillingHeliusRoute
  '/api/v1/billing/helius-setup': typeof ApiV1BillingHeliusSetupRoute
  '/api/v1/billing/invoice': typeof ApiV1BillingInvoiceRoute
  '/api/v1/billing/watch': typeof ApiV1BillingWatchRoute
  '/api/v1/internal/meter': typeof ApiV1InternalMeterRouteWithChildren
  '/api/v1/internal/stats': typeof ApiV1InternalStatsRoute
  '/api/v1/internal/trial-mail': typeof ApiV1InternalTrialMailRoute
  '/api/v1/meter/$': typeof ApiV1MeterSplatRoute
  '/api/v1/storefront/attach': typeof ApiV1StorefrontAttachRoute
  '/api/v1/storefront/checkout': typeof ApiV1StorefrontCheckoutRoute
  '/api/v1/storefront/pricing': typeof ApiV1StorefrontPricingRoute
  '/api/v1/storefront/status': typeof ApiV1StorefrontStatusRoute
  '/api/v1/storefront/trial': typeof ApiV1StorefrontTrialRoute
  '/api/v1/internal/meter/invoices': typeof ApiV1InternalMeterInvoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/meter/pay': typeof MeterPayRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/alerts': typeof AppAlertsRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/policies': typeof AppPoliciesRoute
  '/settings': typeof AppSettingsRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/agents/$id': typeof AppAgentsIdRoute
  '/billing/pay': typeof AppBillingPayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/agents': typeof AppAgentsIndexRoute
  '/billing': typeof AppBillingIndexRoute
  '/api/v1/approvals/$id': typeof ApiV1ApprovalsIdRoute
  '/api/v1/billing/checkout': typeof ApiV1BillingCheckoutRoute
  '/api/v1/billing/config': typeof ApiV1BillingConfigRoute
  '/api/v1/billing/helius': typeof ApiV1BillingHeliusRoute
  '/api/v1/billing/helius-setup': typeof ApiV1BillingHeliusSetupRoute
  '/api/v1/billing/invoice': typeof ApiV1BillingInvoiceRoute
  '/api/v1/billing/watch': typeof ApiV1BillingWatchRoute
  '/api/v1/internal/meter': typeof ApiV1InternalMeterRouteWithChildren
  '/api/v1/internal/stats': typeof ApiV1InternalStatsRoute
  '/api/v1/internal/trial-mail': typeof ApiV1InternalTrialMailRoute
  '/api/v1/meter/$': typeof ApiV1MeterSplatRoute
  '/api/v1/storefront/attach': typeof ApiV1StorefrontAttachRoute
  '/api/v1/storefront/checkout': typeof ApiV1StorefrontCheckoutRoute
  '/api/v1/storefront/pricing': typeof ApiV1StorefrontPricingRoute
  '/api/v1/storefront/status': typeof ApiV1StorefrontStatusRoute
  '/api/v1/storefront/trial': typeof ApiV1StorefrontTrialRoute
  '/api/v1/internal/meter/invoices': typeof ApiV1InternalMeterInvoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/connect': typeof ConnectRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/logos': typeof LogosRoute
  '/meter/pay': typeof MeterPayRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/agents': typeof AppAgentsRouteWithChildren
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/billing': typeof AppBillingRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/policies': typeof AppPoliciesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/oauth/register': typeof OauthRegisterRoute
  '/oauth/token': typeof OauthTokenRoute
  '/_app/agents/$id': typeof AppAgentsIdRoute
  '/_app/billing/pay': typeof AppBillingPayRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/check': typeof ApiV1CheckRoute
  '/api/v1/mcp': typeof ApiV1McpRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/api/v1/approvals/$id': typeof ApiV1ApprovalsIdRoute
  '/api/v1/billing/checkout': typeof ApiV1BillingCheckoutRoute
  '/api/v1/billing/config': typeof ApiV1BillingConfigRoute
  '/api/v1/billing/helius': typeof ApiV1BillingHeliusRoute
  '/api/v1/billing/helius-setup': typeof ApiV1BillingHeliusSetupRoute
  '/api/v1/billing/invoice': typeof ApiV1BillingInvoiceRoute
  '/api/v1/billing/watch': typeof ApiV1BillingWatchRoute
  '/api/v1/internal/meter': typeof ApiV1InternalMeterRouteWithChildren
  '/api/v1/internal/stats': typeof ApiV1InternalStatsRoute
  '/api/v1/internal/trial-mail': typeof ApiV1InternalTrialMailRoute
  '/api/v1/meter/$': typeof ApiV1MeterSplatRoute
  '/api/v1/storefront/attach': typeof ApiV1StorefrontAttachRoute
  '/api/v1/storefront/checkout': typeof ApiV1StorefrontCheckoutRoute
  '/api/v1/storefront/pricing': typeof ApiV1StorefrontPricingRoute
  '/api/v1/storefront/status': typeof ApiV1StorefrontStatusRoute
  '/api/v1/storefront/trial': typeof ApiV1StorefrontTrialRoute
  '/api/v1/internal/meter/invoices': typeof ApiV1InternalMeterInvoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/docs'
    | '/login'
    | '/logos'
    | '/meter/pay'
    | '/partners'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/agents'
    | '/alerts'
    | '/audit'
    | '/billing'
    | '/dashboard'
    | '/inbox'
    | '/policies'
    | '/settings'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/agents/$id'
    | '/billing/pay'
    | '/api/auth/$'
    | '/api/v1/check'
    | '/api/v1/mcp'
    | '/agents/'
    | '/billing/'
    | '/api/v1/approvals/$id'
    | '/api/v1/billing/checkout'
    | '/api/v1/billing/config'
    | '/api/v1/billing/helius'
    | '/api/v1/billing/helius-setup'
    | '/api/v1/billing/invoice'
    | '/api/v1/billing/watch'
    | '/api/v1/internal/meter'
    | '/api/v1/internal/stats'
    | '/api/v1/internal/trial-mail'
    | '/api/v1/meter/$'
    | '/api/v1/storefront/attach'
    | '/api/v1/storefront/checkout'
    | '/api/v1/storefront/pricing'
    | '/api/v1/storefront/status'
    | '/api/v1/storefront/trial'
    | '/api/v1/internal/meter/invoices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/docs'
    | '/login'
    | '/logos'
    | '/meter/pay'
    | '/partners'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/alerts'
    | '/audit'
    | '/dashboard'
    | '/inbox'
    | '/policies'
    | '/settings'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/agents/$id'
    | '/billing/pay'
    | '/api/auth/$'
    | '/api/v1/check'
    | '/api/v1/mcp'
    | '/agents'
    | '/billing'
    | '/api/v1/approvals/$id'
    | '/api/v1/billing/checkout'
    | '/api/v1/billing/config'
    | '/api/v1/billing/helius'
    | '/api/v1/billing/helius-setup'
    | '/api/v1/billing/invoice'
    | '/api/v1/billing/watch'
    | '/api/v1/internal/meter'
    | '/api/v1/internal/stats'
    | '/api/v1/internal/trial-mail'
    | '/api/v1/meter/$'
    | '/api/v1/storefront/attach'
    | '/api/v1/storefront/checkout'
    | '/api/v1/storefront/pricing'
    | '/api/v1/storefront/status'
    | '/api/v1/storefront/trial'
    | '/api/v1/internal/meter/invoices'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/connect'
    | '/docs'
    | '/login'
    | '/logos'
    | '/meter/pay'
    | '/partners'
    | '/privacy'
    | '/signup'
    | '/verify-email'
    | '/_app/agents'
    | '/_app/alerts'
    | '/_app/audit'
    | '/_app/billing'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/_app/policies'
    | '/_app/settings'
    | '/oauth/authorize'
    | '/oauth/register'
    | '/oauth/token'
    | '/_app/agents/$id'
    | '/_app/billing/pay'
    | '/api/auth/$'
    | '/api/v1/check'
    | '/api/v1/mcp'
    | '/_app/agents/'
    | '/_app/billing/'
    | '/api/v1/approvals/$id'
    | '/api/v1/billing/checkout'
    | '/api/v1/billing/config'
    | '/api/v1/billing/helius'
    | '/api/v1/billing/helius-setup'
    | '/api/v1/billing/invoice'
    | '/api/v1/billing/watch'
    | '/api/v1/internal/meter'
    | '/api/v1/internal/stats'
    | '/api/v1/internal/trial-mail'
    | '/api/v1/meter/$'
    | '/api/v1/storefront/attach'
    | '/api/v1/storefront/checkout'
    | '/api/v1/storefront/pricing'
    | '/api/v1/storefront/status'
    | '/api/v1/storefront/trial'
    | '/api/v1/internal/meter/invoices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  LogosRoute: typeof LogosRoute
  MeterPayRoute: typeof MeterPayRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
  OauthRegisterRoute: typeof OauthRegisterRoute
  OauthTokenRoute: typeof OauthTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1CheckRoute: typeof ApiV1CheckRoute
  ApiV1McpRoute: typeof ApiV1McpRoute
  ApiV1ApprovalsIdRoute: typeof ApiV1ApprovalsIdRoute
  ApiV1BillingCheckoutRoute: typeof ApiV1BillingCheckoutRoute
  ApiV1BillingConfigRoute: typeof ApiV1BillingConfigRoute
  ApiV1BillingHeliusRoute: typeof ApiV1BillingHeliusRoute
  ApiV1BillingHeliusSetupRoute: typeof ApiV1BillingHeliusSetupRoute
  ApiV1BillingInvoiceRoute: typeof ApiV1BillingInvoiceRoute
  ApiV1BillingWatchRoute: typeof ApiV1BillingWatchRoute
  ApiV1InternalMeterRoute: typeof ApiV1InternalMeterRouteWithChildren
  ApiV1InternalStatsRoute: typeof ApiV1InternalStatsRoute
  ApiV1InternalTrialMailRoute: typeof ApiV1InternalTrialMailRoute
  ApiV1MeterSplatRoute: typeof ApiV1MeterSplatRoute
  ApiV1StorefrontAttachRoute: typeof ApiV1StorefrontAttachRoute
  ApiV1StorefrontCheckoutRoute: typeof ApiV1StorefrontCheckoutRoute
  ApiV1StorefrontPricingRoute: typeof ApiV1StorefrontPricingRoute
  ApiV1StorefrontStatusRoute: typeof ApiV1StorefrontStatusRoute
  ApiV1StorefrontTrialRoute: typeof ApiV1StorefrontTrialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meter/pay': {
      id: '/meter/pay'
      path: '/meter/pay'
      fullPath: '/meter/pay'
      preLoaderRoute: typeof MeterPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/register': {
      id: '/oauth/register'
      path: '/oauth/register'
      fullPath: '/oauth/register'
      preLoaderRoute: typeof OauthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/token': {
      id: '/oauth/token'
      path: '/oauth/token'
      fullPath: '/oauth/token'
      preLoaderRoute: typeof OauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/agents/$id': {
      id: '/_app/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AppAgentsIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/pay': {
      id: '/_app/billing/pay'
      path: '/pay'
      fullPath: '/billing/pay'
      preLoaderRoute: typeof AppBillingPayRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/check': {
      id: '/api/v1/check'
      path: '/api/v1/check'
      fullPath: '/api/v1/check'
      preLoaderRoute: typeof ApiV1CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/mcp': {
      id: '/api/v1/mcp'
      path: '/api/v1/mcp'
      fullPath: '/api/v1/mcp'
      preLoaderRoute: typeof ApiV1McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/approvals/$id': {
      id: '/api/v1/approvals/$id'
      path: '/api/v1/approvals/$id'
      fullPath: '/api/v1/approvals/$id'
      preLoaderRoute: typeof ApiV1ApprovalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/checkout': {
      id: '/api/v1/billing/checkout'
      path: '/api/v1/billing/checkout'
      fullPath: '/api/v1/billing/checkout'
      preLoaderRoute: typeof ApiV1BillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/config': {
      id: '/api/v1/billing/config'
      path: '/api/v1/billing/config'
      fullPath: '/api/v1/billing/config'
      preLoaderRoute: typeof ApiV1BillingConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/helius': {
      id: '/api/v1/billing/helius'
      path: '/api/v1/billing/helius'
      fullPath: '/api/v1/billing/helius'
      preLoaderRoute: typeof ApiV1BillingHeliusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/helius-setup': {
      id: '/api/v1/billing/helius-setup'
      path: '/api/v1/billing/helius-setup'
      fullPath: '/api/v1/billing/helius-setup'
      preLoaderRoute: typeof ApiV1BillingHeliusSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/invoice': {
      id: '/api/v1/billing/invoice'
      path: '/api/v1/billing/invoice'
      fullPath: '/api/v1/billing/invoice'
      preLoaderRoute: typeof ApiV1BillingInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/billing/watch': {
      id: '/api/v1/billing/watch'
      path: '/api/v1/billing/watch'
      fullPath: '/api/v1/billing/watch'
      preLoaderRoute: typeof ApiV1BillingWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/internal/meter': {
      id: '/api/v1/internal/meter'
      path: '/api/v1/internal/meter'
      fullPath: '/api/v1/internal/meter'
      preLoaderRoute: typeof ApiV1InternalMeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/internal/stats': {
      id: '/api/v1/internal/stats'
      path: '/api/v1/internal/stats'
      fullPath: '/api/v1/internal/stats'
      preLoaderRoute: typeof ApiV1InternalStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/internal/trial-mail': {
      id: '/api/v1/internal/trial-mail'
      path: '/api/v1/internal/trial-mail'
      fullPath: '/api/v1/internal/trial-mail'
      preLoaderRoute: typeof ApiV1InternalTrialMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/meter/$': {
      id: '/api/v1/meter/$'
      path: '/api/v1/meter/$'
      fullPath: '/api/v1/meter/$'
      preLoaderRoute: typeof ApiV1MeterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/storefront/attach': {
      id: '/api/v1/storefront/attach'
      path: '/api/v1/storefront/attach'
      fullPath: '/api/v1/storefront/attach'
      preLoaderRoute: typeof ApiV1StorefrontAttachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/storefront/checkout': {
      id: '/api/v1/storefront/checkout'
      path: '/api/v1/storefront/checkout'
      fullPath: '/api/v1/storefront/checkout'
      preLoaderRoute: typeof ApiV1StorefrontCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/storefront/pricing': {
      id: '/api/v1/storefront/pricing'
      path: '/api/v1/storefront/pricing'
      fullPath: '/api/v1/storefront/pricing'
      preLoaderRoute: typeof ApiV1StorefrontPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/storefront/status': {
      id: '/api/v1/storefront/status'
      path: '/api/v1/storefront/status'
      fullPath: '/api/v1/storefront/status'
      preLoaderRoute: typeof ApiV1StorefrontStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/storefront/trial': {
      id: '/api/v1/storefront/trial'
      path: '/api/v1/storefront/trial'
      fullPath: '/api/v1/storefront/trial'
      preLoaderRoute: typeof ApiV1StorefrontTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/internal/meter/invoices': {
      id: '/api/v1/internal/meter/invoices'
      path: '/invoices'
      fullPath: '/api/v1/internal/meter/invoices'
      preLoaderRoute: typeof ApiV1InternalMeterInvoicesRouteImport
      parentRoute: typeof ApiV1InternalMeterRoute
    }
  }
}

interface AppAgentsRouteChildren {
  AppAgentsIdRoute: typeof AppAgentsIdRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsIdRoute: AppAgentsIdRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppBillingRouteChildren {
  AppBillingPayRoute: typeof AppBillingPayRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingPayRoute: AppBillingPayRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppAlertsRoute: typeof AppAlertsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppAlertsRoute: AppAlertsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiV1InternalMeterRouteChildren {
  ApiV1InternalMeterInvoicesRoute: typeof ApiV1InternalMeterInvoicesRoute
}

const ApiV1InternalMeterRouteChildren: ApiV1InternalMeterRouteChildren = {
  ApiV1InternalMeterInvoicesRoute: ApiV1InternalMeterInvoicesRoute,
}

const ApiV1InternalMeterRouteWithChildren =
  ApiV1InternalMeterRoute._addFileChildren(ApiV1InternalMeterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnectRoute: ConnectRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  LogosRoute: LogosRoute,
  MeterPayRoute: MeterPayRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
  OauthRegisterRoute: OauthRegisterRoute,
  OauthTokenRoute: OauthTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1CheckRoute: ApiV1CheckRoute,
  ApiV1McpRoute: ApiV1McpRoute,
  ApiV1ApprovalsIdRoute: ApiV1ApprovalsIdRoute,
  ApiV1BillingCheckoutRoute: ApiV1BillingCheckoutRoute,
  ApiV1BillingConfigRoute: ApiV1BillingConfigRoute,
  ApiV1BillingHeliusRoute: ApiV1BillingHeliusRoute,
  ApiV1BillingHeliusSetupRoute: ApiV1BillingHeliusSetupRoute,
  ApiV1BillingInvoiceRoute: ApiV1BillingInvoiceRoute,
  ApiV1BillingWatchRoute: ApiV1BillingWatchRoute,
  ApiV1InternalMeterRoute: ApiV1InternalMeterRouteWithChildren,
  ApiV1InternalStatsRoute: ApiV1InternalStatsRoute,
  ApiV1InternalTrialMailRoute: ApiV1InternalTrialMailRoute,
  ApiV1MeterSplatRoute: ApiV1MeterSplatRoute,
  ApiV1StorefrontAttachRoute: ApiV1StorefrontAttachRoute,
  ApiV1StorefrontCheckoutRoute: ApiV1StorefrontCheckoutRoute,
  ApiV1StorefrontPricingRoute: ApiV1StorefrontPricingRoute,
  ApiV1StorefrontStatusRoute: ApiV1StorefrontStatusRoute,
  ApiV1StorefrontTrialRoute: ApiV1StorefrontTrialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
